# Generated by Django 6.0.2 on 2026-02-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imag',
            field=models.ImageField(blank=True, upload_to='course/'),
        ),
    ]
