# Generated by Django 6.0.2 on 2026-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_alter_lesson_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
